// <auto-generated />
using System;
using System.Collections.Generic;
using WunderkindLC.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace WunderkindLC.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260618120000_AddCourseProgressCourseId")]
    partial class AddCourseProgressCourseId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WunderkindLC.Domain.CourseProgress", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CourseId")
                        .HasColumnType("text");

                    b.Property<bool>("Done")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StudentId", "ItemId")
                        .IsUnique();

                    b.HasIndex("StudentId", "CourseId", "ItemId")
                        .IsUnique()
                        .HasName("ix_course_progress_course_tracking")
                        .HasFilter("\"CourseId\" IS NOT NULL");

                    b.ToTable("CourseProgresses");
                });

#pragma warning restore 612, 618
        }
    }
}
